services:
  bind9:
    container_name: dns
    image: ubuntu/bind9:9.18-23.04_edge
    environment:
      - BIND9_USER=root
      - TZ=Europe/Stockholm
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    networks:
      backend:
        ipv4_address: 192.168.50.132
    volumes:
      - ./config/:/etc/bind:rw
    restart: unless-stopped

networks:
  backend:
    external: true
