services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '80:80/tcp'
    environment:
      TZ: 'Europe/Stockholm'
      WEBPASSWORD: ${PASSWD}
    volumes:
      - etc_pihole:/etc/pihole
      - etc_dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped
    networks:
      backend:
        ipv4_address: 10.10.10.100

volumes:
  etc_pihole:
  etc_dnsmasq:

networks:
  backend:
    external: true
