services:
  immich_server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - DB_HOSTNAME=immich_postgres
      - REDIS_HOSTNAME=immich_redis
      - UPLOAD_LOCATION=${IMMICH_UPLOAD_LOCATION}
      - IMMICH_VERSION=${IMMICH_VERSION}
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - DB_USERNAME=${IMMICH_DB_USERNAME}
      - DB_DATABASE_NAME=${IMMICH_DB_NAME}
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    networks:
      backend:
        ipv4_address: 10.10.10.107

  immich_microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'microservices']
    volumes:
      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - DB_HOSTNAME=immich_postgres
      - REDIS_HOSTNAME=immich_redis
      - UPLOAD_LOCATION=${IMMICH_UPLOAD_LOCATION}
      - IMMICH_VERSION=${IMMICH_VERSION}
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - DB_USERNAME=${IMMICH_DB_USERNAME}
      - DB_DATABASE_NAME=${IMMICH_DB_NAME}
    depends_on:
      - redis
      - database
    restart: always
    networks:
      backend:
        ipv4_address: 10.10.10.108

  immich_machine_learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model_cache:/cache
    env_file:
      - DB_HOSTNAME=immich_postgres
      - REDIS_HOSTNAME=immich_redis
      - UPLOAD_LOCATION=${IMMICH_UPLOAD_LOCATION}
      - IMMICH_VERSION=${IMMICH_VERSION}
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - DB_USERNAME=${IMMICH_DB_USERNAME}
      - DB_DATABASE_NAME=${IMMICH_DB_NAME}
    restart: always
    networks:
      backend:
        ipv4_address: 10.10.10.109

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always
    networks:
      backend:
        ipv4_address: 10.10.10.110

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_USER: ${IMMICH_DB_USERNAME}
      POSTGRES_DB: ${IMMICH_DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      backend:
        ipv4_address: 10.10.10.111

volumes:
  pgdata:
  model_cache:

networks:
  backend:
    external: true
