services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    networks:
      backend:
        ipv4_address: 10.10.10.112
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: ${DATA_LOCATION}/library
        target: /media
    restart: always
    environment:
      - JELLYFIN_PublishedServerUrl=https://play.psmhome.se

networks:
  backend:
    external: true
