services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - '9443:9443'
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      backend:
        ipv4_address: 192.168.50.135

volumes:
  data:

networks:
  backend:
    external: true
