---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: true
    memory: true
    disk: /

- openweathermap:
    label: Norrköping
    latitude: 58.5867021
    longitude: 16.1430553
    units: metric
    apiKey: {{HOMEPAGE_VAR_OPENWEATHERMAP_KEY}}
    format:
      maximumFractionDigits: 1

- search:
    provider: [google, duckduckgo]
    showSearchSuggestions: true
    target: _blank

- datetime:
    locale: sv
    format:
      timeStyle: short
      dateStyle: long
