name: ansible
on: [push]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy caddy
        run: cd caddy && docker compose up -d
